### ISSUE TITLE
Design upcoming deadlines section

### ISSUE THREAD

**Issue by mottur** [CSE-210-Team-10/group10-esc012#102]
Task
- Design upcoming deadline calendar view (week)

Deliverables
- Figma design includes upcoming deadline calendar view (week)

**Comment by kalechip22** [comment]
Added changes to the upcoming deadline area so that it shows next 7 days and overdue
![{63AD7A15-CC33-4BB0-825B-34456A2BB511}](https://github.com/user-attachments/assets/e3db712f-501b-41b8-be6f-3a23605f5074)

**Comment by kalechip22** [comment]
Changed separation of overdue and upcoming deadlines
![{463A730E-9F47-4D8A-95C7-84D6BBF9B479}](https://github.com/user-attachments/assets/0a39de53-4225-4877-9203-493d9e0a3ea2)

**Comment by kalechip22** [comment]
Design accepted and finalized
