### ISSUE TITLE
Design of filter popover

### ISSUE THREAD

**Issue by mottur** [CSE-210-Team-10/group10-esc012#103]
Task
- Design the filter popover

Deliverables
- Figma design includes filter popover

**Comment by kalechip22** [comment]
Created filter popup options when button is clicked
![{D6D7E6B6-82A3-40DC-AAD4-A2F87476F289}](https://github.com/user-attachments/assets/5c3bb5a1-71a2-4424-80e8-b27d4c7ca682)
