### ISSUE TITLE
Design create and edit task popovers

### ISSUE THREAD

**Issue by mottur** [CSE-210-Team-10/group10-esc012#104]
Task
- Design create and edit task popovers

Deliverables
- Figma design includes create and edit task popovers

**Comment by kalechip22** [comment]
Added views to edit tasks and add them
![{72B5C8E9-EA15-4C8E-82DC-82F8CDE07C06}](https://github.com/user-attachments/assets/f0adf48e-ce12-4ee3-852d-d00391fdddfa)
