### ISSUE TITLE
Design relevant links section

### ISSUE THREAD

**Issue by mottur** [CSE-210-Team-10/group10-esc012#105]
Task
- Design relevant links section

Deliverables
- Figma design includes relevant links section

**Comment by kalechip22** [comment]
Relevant links section with icons added and did popup too
![{D14301C3-5430-4A6C-9579-6D67AD019BAF}](https://github.com/user-attachments/assets/cbe6bbe0-4ab2-447b-9009-fa876e6f57dc)
