### ISSUE TITLE
Write unit tests for src/js/task functions

### ISSUE THREAD

**Issue by mottur** [CSE-210-Team-10/group10-esc012#123]
Task
- Write unit tests for src/js/task functions

Deliverables
- Unit tests in the test folder for src/js/task functions

Size Estimation: Medium (2-4 hours)

**Comment by kalechip22** [comment]
Added unit tests, paired with signout button implementation

**Comment by sbogh** [comment]
Linked to #134

**Comment by kalechip22** [comment]
Redid some tests and fixed errors for them in crud.js
