### ISSUE TITLE
Highlight urgent deadlines: As a user, I need to know the tasks that are due this week so that I don’t forget to prioritize and complete them in time.

### ISSUE THREAD

**Issue by mottur** [CSE-210-Team-10/group10-esc012#20]
Task
- Create urgent deadlines feature of the dashboard.

Deliverables
- Working urgent deadlines section with a list of tasks containing the task name, due date, priority, and links, all sorted by due date.

Size Estimation: Large (5+ hours)

**Comment by kalechip22** [comment]
Highlights overdue task and task due by the next 7 days with priority selection

**Comment by mottur** [comment]
Completed.
