### ISSUE TITLE
Show upcoming deadlines for all tasks: As a user, I want to know which tasks have deadlines coming up so that I can effectively distribute my time and complete all my tasks before their deadlines.

### ISSUE THREAD

**Issue by mottur** [CSE-210-Team-10/group10-esc012#21]
Task
- Add due dates and priorities to tasks grouping section of the dashboard.

Deliverables
- Working grouping section of the dashboard including due dates, priorities, and the ability to filter by priority.

Size Estimation: Large (5+ hours)

**Comment by kalechip22** [comment]
Added so that it updates to the next 7 days for upcoming deadlines

**Comment by mottur** [comment]
Completed.
