### ISSUE TITLE
Deliver Requested GitHub Content for Integration

### ISSUE THREAD

**Issue by sbogh** [CSE-210-Team-10/group10-esc012#32]
Task
- Based on the outcome of the meeting with the front end team, deliver the requested data in a condensed format to the front end in an agreed upon format.

Deliverables
- Code that filters the raw GitHub returned json file and provides only essential data to the front end.
- Documentation of the code and the GitHub API usage
- Unit testing for edge cases of data misses as well as normal operation to ensure code operates as expected

**Comment by sammedkamate** [comment]
enabled API for fetching issues with a particular user
