### ISSUE TITLE
Ensure Tasks Can Be Filtered

### ISSUE THREAD

**Issue by sbogh** [CSE-210-Team-10/group10-esc012#50]
Task
- Ensure that tasks can be filtered based on tags assigned to the structure object and implement functionality to perform the filtering.

Deliverables
- Functions that allow filtering based on the task object structure

**Comment by sbogh** [comment]
Pushed to Sprint 4, delivery by 12/6

**Comment by mottur** [comment]
From PR by @Yuxuan-Wu:
- Methods for task filtering based on type, status, time implemented
- Methods for task sorting from new to old and new to old implemented
