### ISSUE TITLE
Implement HTMLHint

### ISSUE THREAD

**Issue by sbogh** [CSE-210-Team-10/group10-esc012#66]
Task
- Implement HTMLHint

Deliverables
- Additions to the pipeline code that integrates and adds HTML linting

**Comment by sbogh** [comment]
Delivery: 12/6

**Comment by kalechip22** [comment]
Added the HTML linter and an HTML parser with standard rules. Tested with npm lint and received error output.

**Comment by kalechip22** [comment]
Changed to HTML hint.

**Comment by mottur** [comment]
Completed.
