### ISSUE TITLE
Read and store dashboard state in local json file

### ISSUE THREAD

**Issue by sbogh** [CSE-210-Team-10/group10-esc012#67]
Task
- Store state of dashboard to a local json file in browser
- Hash/obfuscate the json file
- Read from local json file to restore state to dashboard

Deliverables
- Functions to store and read json file when dashboard is opened or closed, as well as at specific time intervals (every X hours the dashboard is logged in for to ensure no state loss)

**Comment by sbogh** [comment]
Delivery: 12/7

**Comment by mottur** [comment]
From PR by @davidtso1219:
- Renamed <task> custom component to <task-item> for better naming convention
- Updated build script to handle import CSS in JS
- Added CRUD + filter operations for task objects
- Used <task-item> to populate data in index.html
